# Generated by Django 5.0.6 on 2024-05-14 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/generated_cards/')),
                ('preset', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OutlineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='assets/card_outlines/')),
            ],
        ),
        migrations.CreateModel(
            name='SlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='assets/card_slots/')),
            ],
        ),
        migrations.CreateModel(
            name='CardPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slots', models.ManyToManyField(to='generator.cardslot')),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.outlineimage')),
            ],
        ),
        migrations.AddField(
            model_name='cardslot',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.slotimage'),
        ),
    ]
