# Generated by Django 5.0.6 on 2024-05-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='preset',
            new_name='preset_json',
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='generated_cards/'),
        ),
    ]
