# Generated by Django 5.0.6 on 2024-05-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_rename_preset_card_preset_json_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='generator.cardpreset'),
        ),
    ]
