# Generated by Django 5.0.6 on 2024-05-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_card_preset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-id']},
        ),
    ]
