# Generated by Django 5.0.6 on 2024-05-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_alter_card_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='assets/gem_slots/')),
            ],
        ),
        migrations.AddField(
            model_name='cardslot',
            name='gem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.gemimage'),
        ),
    ]
