# Generated by Django 5.0.6 on 2024-05-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_gemimage_cardslot_gem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardslot',
            name='text',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
