# Generated by Django 5.0.6 on 2024-05-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_cardslot_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardslot',
            name='font',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
