# Generated by Django 5.0.6 on 2024-05-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_cardslot_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardslot',
            name='text_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
